import jsPDF from 'jspdf';
import html2canvas from 'html2canvas';
import { format } from 'date-fns';

export const exportToPDF = async (itinerary, tripDetails) => {
    const pdf = new jsPDF('p', 'mm', 'a4');
    const pageWidth = pdf.internal.pageSize.getWidth();
    const pageHeight = pdf.internal.pageSize.getHeight();
    const margin = 15;
    let yPosition = margin;

    pdf.setFont('helvetica', 'bold');
    pdf.setFontSize(24);
    pdf.setTextColor(14, 165, 233);
    pdf.text('SafarSetu', margin, yPosition);
    
    yPosition += 8;
    pdf.setFontSize(20);
    pdf.setTextColor(0, 0, 0);
    pdf.text(`Trip to ${tripDetails.destination?.name || 'Destination'}`, margin, yPosition);
    
    yPosition += 10;
    pdf.setFont('helvetica', 'normal');
    pdf.setFontSize(11);
    pdf.setTextColor(100, 100, 100);
    
    const dateRange = `${format(new Date(tripDetails.startDate), 'MMM dd, yyyy')} - ${format(new Date(tripDetails.endDate), 'MMM dd, yyyy')}`;
    pdf.text(dateRange, margin, yPosition);
    
    yPosition += 6;
    pdf.text(`${tripDetails.travelers} Traveler${tripDetails.travelers > 1 ? 's' : ''} • ${tripDetails.travelStyle} • ${tripDetails.budget} Budget`, margin, yPosition);
    
    yPosition += 12;
    pdf.setDrawColor(200, 200, 200);
    pdf.line(margin, yPosition, pageWidth - margin, yPosition);
    yPosition += 10;

    itinerary.days.forEach((day, dayIndex) => {
        if (yPosition > pageHeight - 40) {
            pdf.addPage();
            yPosition = margin;
        }

        pdf.setFont('helvetica', 'bold');
        pdf.setFontSize(16);
        pdf.setTextColor(0, 0, 0);
        pdf.text(`Day ${day.day} - ${format(new Date(day.date), 'EEEE, MMM dd')}`, margin, yPosition);
        yPosition += 8;

        day.activities.forEach((activity) => {
            if (yPosition > pageHeight - 30) {
                pdf.addPage();
                yPosition = margin;
            }

            pdf.setFont('helvetica', 'bold');
            pdf.setFontSize(12);
            pdf.setTextColor(14, 165, 233);
            const timeLabel = activity.time.charAt(0).toUpperCase() + activity.time.slice(1);
            pdf.text(`${timeLabel}:`, margin + 5, yPosition);
            
            pdf.setFont('helvetica', 'normal');
            pdf.setTextColor(0, 0, 0);
            pdf.text(activity.name, margin + 30, yPosition);
            yPosition += 6;

            pdf.setFontSize(10);
            pdf.setTextColor(100, 100, 100);
            const description = pdf.splitTextToSize(activity.description, pageWidth - margin * 2 - 10);
            pdf.text(description, margin + 5, yPosition);
            yPosition += description.length * 5;

            if (activity.duration) {
                pdf.text(`Duration: ${activity.duration}`, margin + 5, yPosition);
                yPosition += 5;
            }

            if (activity.notes) {
                pdf.setFont('helvetica', 'italic');
                pdf.setTextColor(150, 150, 150);
                const notes = pdf.splitTextToSize(`Note: ${activity.notes}`, pageWidth - margin * 2 - 10);
                pdf.text(notes, margin + 5, yPosition);
                yPosition += notes.length * 5;
            }

            yPosition += 5;
        });

        if (day.notes) {
            if (yPosition > pageHeight - 20) {
                pdf.addPage();
                yPosition = margin;
            }
            pdf.setFont('helvetica', 'italic');
            pdf.setFontSize(10);
            pdf.setTextColor(100, 100, 100);
            const dayNotes = pdf.splitTextToSize(`Day Notes: ${day.notes}`, pageWidth - margin * 2);
            pdf.text(dayNotes, margin, yPosition);
            yPosition += dayNotes.length * 5;
        }

        yPosition += 8;
        if (dayIndex < itinerary.days.length - 1) {
            pdf.setDrawColor(220, 220, 220);
            pdf.line(margin, yPosition, pageWidth - margin, yPosition);
            yPosition += 10;
        }
    });

    const footerY = pageHeight - 10;
    pdf.setFontSize(8);
    pdf.setTextColor(150, 150, 150);
    pdf.text('Generated by SafarSetu - Your Personal Travel Companion', pageWidth / 2, footerY, { align: 'center' });

    const fileName = `${tripDetails.destination?.name || 'Trip'}_Itinerary_${format(new Date(), 'yyyy-MM-dd')}.pdf`;
    pdf.save(fileName);
};

export const exportElementToPDF = async (elementId, fileName = 'itinerary.pdf') => {
    const element = document.getElementById(elementId);
    if (!element) {
        console.error('Element not found');
        return;
    }

    const canvas = await html2canvas(element, {
        scale: 2,
        useCORS: true,
        logging: false,
    });

    const imgData = canvas.toDataURL('image/png');
    const pdf = new jsPDF('p', 'mm', 'a4');
    const pdfWidth = pdf.internal.pageSize.getWidth();
    const pdfHeight = pdf.internal.pageSize.getHeight();
    const imgWidth = canvas.width;
    const imgHeight = canvas.height;
    const ratio = Math.min(pdfWidth / imgWidth, pdfHeight / imgHeight);
    const imgX = (pdfWidth - imgWidth * ratio) / 2;
    const imgY = 0;

    pdf.addImage(imgData, 'PNG', imgX, imgY, imgWidth * ratio, imgHeight * ratio);
    pdf.save(fileName);
};
